### ISSUE TITLE
offline-ingest: unable to decode JPX image data

### ISSUE THREAD

**Issue by lydiam** [FLVC/offline-ingest#10]
Approximately 300 PDFs to date (DigiTool SMC collection) load without thumbnails and give the following warning:

4.91 sec,  8.45 MB  PdfPackage::FADT3318708 (fau:950) => collection: fau:smc, palmm:smc, "Know your enemy, Japan"
    Warnings:
    When creating a thumbnail image from the PDF with command '/usr/bin/convert -quality 75 -colorspace RGB' the following message was produced:
    error: cannot decode code stream
    unable to decode JPX image data.
    ***\* Warning: File has insufficient data for an image.
    ***\* This file had errors that were repaired or ignored.
    ***\* The file was produced by:
    ***\* >>>> Adobe Acrobat 8.0 Paper Capture Plug-in <<<<
    ***\* Please notify the author of the software that produced this
    ***\* file that it does not conform to Adobe's published PDF
    ***\* specification.
    When creating a preview image from the PDF with command '/usr/bin/convert -quality 75 -colorspace RGB' the following message was produced:
    error: cannot decode code stream
    unable to decode JPX image data.
    ***\* Warning: File has insufficient data for an image.
    ***\* This file had errors that were repaired or ignored.
    ***\* The file was produced by:
    ***\* >>>> Adobe Acrobat 8.0 Paper Capture Plug-in <<<<
    ***\* Please notify the author of the software that produced this
    ***\* file that it does not conform to Adobe's published PDF
    ***\* specification.

Manny did some investigating on 10/16/2013 and said the following:

"I checked on the server, it looks like ImageMagick, the tool we're using to create the thumbnails is an old version (6.5.4-7 2012-04-10), and upgrading it to the latest stable (6.8.6-9 2013-08-25) might fix this. I've done some googling and similar errors have been resolved by reinstalling it, so I've got my fingers crossed."

**Comment by glewisorg** [comment]
Ghostscript 8.70 was installed to resolve the issue.
