### ISSUE TITLE
"hangups" interrupt processing, even when run with nohup

### ISSUE THREAD

**Issue by lydiam** [FLVC/offline-ingest#12]
The package program quits with a hangup message:

From Priscilla's email:

This is the command I use (where 1980 could be any year).  The hangup seems to happen at least once a day (although not yesterday), sometimes twice.   Once only a dozen pages were loaded, once over 400 were (sob) .

[pcaplan@islandorap FSU_prospective]$ nohup package --prospective --server fsu7p
rod /ssa/d2i/FSU_prospective/FSUYB_1980 &>$HOME/FSUYB_1980.prodlog &

**Comment by grf** [comment]
This was fixed long ago: we properly catch HUPs, and recently resources on the systems have been greatly increased.
