### ISSUE TITLE
package program gives errors in loading JP2 files

### ISSUE THREAD

**Issue by lydiam** [FLVC/offline-ingest#18]
JP2 files are now not loading via the "package" program.  Files loaded Jan. 2 on the production server now won't load into islandload-test and give the following errors:

Issues creating Medium datastream
    When creating a resized image (500x700) from the image '/ssa/d2i/FAU_ACWD_jp2_converted/FADT3171686/3171686_22.jp2' with command '/usr/bin/convert -compress LZW' the following message was encountered:
    error: cannot decode code stream
    convert: unable to decode image file 

New packages containing JP2 files give the same error on islandload-prd.

Examples of directories of packages that failed with this error:

/ssa/d2i/FAU_CWPW_jp2_converted
/ssa/d2i/FAU_CWL_jp2_converted
/ssa/d2i/FAU_CWP_jp2_converted

Loading with --test flag gives no indication of errors.

**Comment by lydiam** [comment]
This is a high priority problem

**Comment by grf** [comment]
I know what the fix is, will take several hours to complete

**Comment by lydiam** [comment]
Any progress on this?

**Comment by grf** [comment]
Fixed and installed as of 2015-01-09 -  Certain JP2s are problematic for ImageMagick utilities,  we now punt to kakdu properly in all cases (resized/reporting size/converting) that ImageMagick fails.

**Comment by lydiam** [comment]
The package program is now logging messages out of order, with "Invalid Package" errors coming before the detailed error and other package messages in between for example (from /home/lydiam/FAU_CWP_jp2.prodlog2):

22.84 sec, 28.05 MB  LargeImagePackage::FADT3171621 (fau:17072) => collection: fau:cwp, "Confederate Photo"
Invalid package in /ssa/d2i/FAU_CWP_jp2_converted/FADT3172063.<----------------
25.85 sec, 45.50 MB  LargeImagePackage::FADT3172062 (fau:17073) => collection: fau:cwp, "Confederate Buildings"
 0.00 sec,  0.00 MB  LargeImagePackage::FADT3172063 (no pid) => no collections, ""
    Errors:
    The IID for this package, FADT3172063, is alreading being used for islandora object fau:16791. The IID must be unique.

Invalid package in /ssa/d2i/FAU_CWP_jp2_converted/FADT3172066. <-------------
42.06 sec, 84.33 MB  LargeImagePackage::FADT3172064 (fau:17074) => collection: fau:cwp, "Confederate Buildings"
 0.00 sec,  0.00 MB  LargeImagePackage::FADT3172066 (no pid) => no collections, ""
    Errors:
    The IID for this package, FADT3172066, is alreading being used for islandora object fau:16793. The IID must be unique.

Invalid package in /ssa/d2i/FAU_CWP_jp2_converted/FADT3172068.
14.43 sec, 17.86 MB  LargeImagePackage::FADT3172067 (fau:17075) => collection: fau:cwp, "Confederate Buildings"

**Comment by grf** [comment]
On Thu, Jan 15, 2015 at 3:39 PM, Lydia Motyka <notifications@github.com>
wrote:

> The package program is now logging messages out of order, with "Invalid
> Package" errors coming before the detailed error and other package messages
> in between for example (from /home/lydiam/FAU_CWP_jp2.prodlog2):
>

Part of this is as it's always been - certain kinds of invalid package
errors always came first.

The other interleaving is probably because sometimes errors write to
standard output, some to standard error -  that can certainly interleave
the different package reports.  That's trivially fixable.

When would you like me to roll out the fix?

-Randy
