### ISSUE TITLE
Obtain book loading stats

### ISSUE THREAD

**Issue by lydiam** [FLVC/offline-ingest#24]
Per Randy, estimates of how long it takes to load books are directly related to Tesseract processing speed.  Randy will provide a formula for use in estimating load times for remaining DigiTool books.

**Comment by grf** [comment]
MD asks for the data to be broken down by image type.

**Comment by grf** [comment]
Using the offline-ingest database I ran

      select extract('epoch' from time_finished) - extract('epoch' from time_started) as seconds, bytes_ingested
	from islandora_packages
       where success = true
	 and content_model = 'islandora:bookCModel'
    order by bytes_ingested;

I broke out the above output into two separate files, 'times.dat' and
'sizes.dat'.  Then, in octave (using tutorial http://www.lauradhamilton.com/tutorial-linear-regression-with-octave):

    t=load('times.dat');
    s=load('sizes.dat');

    x = s ./ (1024 * 1024 * 1024);
    y = t ./ 3600;

    scatter(x, y)

    m = length(x)
    X = [ones(m,1) x];

    ylabel('Processing Time in Hours')
    xlabel('Book Size in GBytes')

    X = [ones(m,1) x];

    theta = (pinv(X'*X))*X'*y
       0.61817
       0.26687

    hold on
    plot(X(:,2), X*theta, '-')

Result:

     Hours processing =  (Size in GB) * 0.267 + 0.618



![fitted-scatterplot](https://cloud.githubusercontent.com/assets/35888/6644758/ff6b1da4-c98c-11e4-8175-dea760e45f02.png)

**Comment by lydiam** [comment]
This doesn't seem right:  UF has approx. 1,700 books for a total of 69GB.

69 * 0.267 + 0.618 = 19.041

There's no way that 1,700 books will load in 19 hours.

**Comment by grf** [comment]
Are they really an average of 41 MB/book?    Seems unlikely.   Are they
really images,  or are most of them PDFs or other text?

Our books average 1.2 GB each package.

**Comment by lydiam** [comment]
Why unlikely?  There are about 100,000 pages, ~32,000 JPG and 73,000 JP2.  The packages contain PDFs as well, so the 69GB is not exact and the actual total size will be smaller because the PDFs won’t be loaded.  All of the UF books are in /ssa/d2i/UF_all_books_converted/.

Lydia

**Comment by grf** [comment]
On Wed, Apr 8, 2015 at 12:36 PM, Lydia Motyka <notifications@github.com>
wrote:

> Why unlikely? There are about 100,000 pages, ~32,000 JPG and 73,000 JP2.
> The packages contain PDFs as well, so the 69GB is not exact and the actual
> total size will be smaller because the PDFs won't be loaded. All of the UF
> books are in /ssa/d2i/UF_all_books_converted/.
>


Looks like UF has done a really bang-up job creating the JP2,  with very
good compressions.

So for this batch,  the 19 hours is an under-estimate.   Our estimates will
get better with more examples,  from diverse accessions.

MD's suggestion (which I haven't gotten back too) is very apropos in
developing

-Randy

**Comment by grf** [comment]
On Wed, Apr 8, 2015 at 12:12 PM, Lydia Motyka <notifications@github.com>
wrote:

> This doesn't seem right: UF has approx. 1,700 books for a total of 69GB.
>
> 69 * 0.267 + 0.618 = 19.041
>
> There's no way that 1,700 books will load in 19 hours
>

Yeah,   the more I look at that the more I scratched my head - it's way
low,  but I know my statistics aren't that off.

The problem is in the algebra.  To see this, say we had 3 packages, a,b,c
each 1 GB.  To figure out what it's going to take:


a:   1 * 0.267  + 0.618  = 0.885 hours
b:   1 * 0.267  + 0.618  = 0.885 hours
c:   1 * 0.267  + 0.618  = 0.885 hours

or 2.66 hours.

The problem's applying the estimate for one package to an aggregate number
of packages.  What we should be doing is:

(total # GB) * 0.267 + (total # packages) * 0.618

or

    69 * 0.267 +  1750 * 0.618  = 1100 hours

call it 46 days.

That's more like it.

I'm embarrassed my basic algebra is soooo rusty.

**Comment by lydiam** [comment]
That does seem to be more accurate, and fortunately it’s also in line with the June deadline.
